### ISSUE TITLE
Accessibility related problem: Can't use an undefined value as an ARRAY reference

### ISSUE THREAD

**Issue by ysangkok** [derf/Travel-Routing-DE-VRR#6]
```
 % efa Darmstadt Stuttgart
Can't use an undefined value as an ARRAY reference at /home/janus/perl5/bin/efa line 239.
```

**Comment by derf** [comment]
Is that really your commandline? What you should be getting in that case is

```Usage: efa [options] <from-city> <from-stop> <to-city> <to-stop>
See also: man efa
```

**Comment by ysangkok** [comment]
Yes. Even if I used an example from the man page, like `efa Do Hbf MH Hbf`, I still had this problem. But the fix fixes the problem. Thanks.

**Comment by derf** [comment]
Sorry for the mistake in my first reply, I simply forgot to pull before trying to verify the issue on this machine :)
