### ISSUE TITLE
How to install globally?

### ISSUE THREAD

**Issue by fbrinker** [derf/Travel-Routing-DE-VRR#8]
Hello,

I would like to install **efa** globally / make it available for all users on my system. I am using a script for Conky and Polybar that shows me the next available trains for my route including a possible delay. Works fine if I start conky or polybar with my current user, I built the project with, because **efa** is installed in /home/fbrinker/perl5. But even using /home/fbrinker/perl5/bin/efa in my scripts didn't work for other users because they miss the libraries.

I've tried building the project with sth like this `perl Build.PL --install_base /usr/lib/perl5/site_perl` and other pathes "i could find", but I didn't get it to work. At the end **efa** was available but not the lib Travel/Routing...

What would be the right way to solve this?

My build script looks like this (building from a repo clone):
```bash
cd Travel-Routing-DE-VRR

cpan Module::Build
perl Build installdeps

perl Build.PL
#perl Build.PL --install_base /usr/share/perl5
#perl Build.PL --install_base /usr/lib/perl5/site_perl
./Build
./Build manifest

sudo ./Build install
```

Many thanks in advance,
Florian

**Comment by derf** [comment]
On most systems that should work just fine, though depending on your umask `Build install` doesn't always get the permissions right. Try running `sudo chmod -R a+rX /usr/local/share/perl` (replace path as appropriate) after installation.

**Comment by fbrinker** [comment]
Hmm I've tried the following pathes
```
#perl Build.PL --install_base /usr/share/perl5
#perl Build.PL --install_base /usr/lib/perl5/site_perl
#perl Build.PL --install_base /usr/share/perl5/site_perl
```

Even with the updated permissions i'didn't get it to work and got the following message
```
Can't locate Travel/Routing/DE/EFA.pm in @INC (you may need to install the Travel::Routing::DE::EFA module) (@INC contains: /usr/lib/perl5/5.26/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.26/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.26/core_perl /usr/share/perl5/core_perl) at /usr/lib/perl5/site_perl/bin/efa line 14.
BEGIN failed--compilation aborted at /usr/lib/perl5/site_perl/bin/efa line 14.
```
I've installed it as root user for now. That works fine, hm :)
